Section "ServerLayout"
    Identifier "CH347Layout"
    Screen 0 "CH347Screen"
EndSection

Section "Device"
    Identifier "CH347Dummy"
    Driver "dummy"
    VideoRam 16384
EndSection

Section "Monitor"
    Identifier "CH347Monitor"
    HorizSync 5.0-100.0
    VertRefresh 5.0-100.0
    Modeline "320x480" 12.00 320 336 368 400 480 483 493 500
EndSection

Section "Screen"
    Identifier "CH347Screen"
    Device "CH347Dummy"
    Monitor "CH347Monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "320x480"
        Virtual 320 480
    EndSubSection
EndSection
